apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-password
  labels:
    app: mosquitto
data:
  password.txt: |
    admin:$6$Dkc/7RZS6eAUAU9g$kmIC9y1XMwGthGcOeuQhuaqwxsJnJhEjbMOFz8TYm1nCFJ5SXzpozeN835qiHyvr/GUV0VUKsaWIIb49Iw8Vqg==